- hosts: localhost

  vars:
    mysql_user: mysql
    mysql_group: mysql

    mysql_root_password: Operate123

    data_path: /data

    sonar_db_user: sonar
    sonar_db_pass: sonar
    sonar_db_name: sonar

  tasks:
    - name: Copy configuration file
      template: src=templates/my.cnf.j2 dest=/etc/my.cnf

    - name: Install default database
      command: mysql_install_db --user={{ mysql_user }} --datadir={{ data_path }}/mysql

    - name: Copy configuration file
      template: src=templates/init.sql.j2 dest=/data/init.sql

    - name: Start mysqld to setup the user and database
      service: name=mysqld state=started

    - name: Copy todolist user creation file
      template: src=templates/sonarqube.sql.j2 dest=/data/sonarube.sql group={{ mysql_group }} owner={{ mysql_user }}

    - name: Execute the todolist user creation
      shell: mysql -u root -p{{ mysql_root_password }} < /data/sonarqube.sql

    - name: Stop mysqld
      service: name=mysqld state=stopped
