- hosts: localhost

  tasks:
    - name: Build images
      command: docker build -t lotaris/{{ item }} {{ item }}
      with_items:
        - bash
        - serf-srv
      # - unicorn-rbenv
      # - redis-data
      # - redis-srv
      # - pg-data
      # - pg-srv
      # - pg-init
      # - rox-center
      # - rox-center-commander
      # - resque
      # - nginx
        - java-serf
        - glassfish-base
        - jenkins-base
        - mysql-data
        - mysql-srv
        - mysql-init
      # - sonarqube-mysql-init
      # - sonarqube-srv
        - glassfish-data
        - glassfish-node
        - jenkins-srv
        - nginx-glassfish-lb
        - nginx-angular-lb
        - nginx-angular-data
        - nginx-angular-node

    # - name: Docker cleanup
    #   shell: "docker rmi $(docker images -f 'dangling=true' -q)"

    - name: Start serf server
      command: docker run -dP --name serf-gf-cluster lotaris/serf-srv

    - name: Prepare data container for todolist backend
      command: docker run -v /data --name mysql-data lotaris/mysql-data

    - name: Inialize mysql for todolist backend
      command: docker run --rm --volumes-from mysql-data lotaris/mysql-init

    - name: Start mysql container for todolist backend
      command: docker run -dP --volumes-from mysql-data --name mysql-srv lotaris/mysql-srv

    - name: Prepare data container for glassfish and jenkins
      command: docker run -v /artifacts --name gf-data lotaris/glassfish-data

    - name: Prepare data container for todolist frontend
      command: docker run -v /frontend --name nginx-angular-data lotaris/nginx-angular-data

    - name: Start Jenkins container for todolist backend
      command: docker run -dP --volumes-from gf-data --volumes-from nginx-angular-data --link /mysql-srv:mysql-srv --link /serf-gf-cluster:serf-gf-cluster --name jenkins-srv lotaris/jenkins-srv

    - name: Start the Glassfish Load balancer
      command: docker run -dP --link /serf-gf-cluster:serf-gf-cluster --name nginx-gf-lb lotaris/nginx-glassfish-lb

    - name: Start the Angular Load balancer
      command: docker run -dP --link /serf-gf-cluster:serf-gf-cluster --name nginx-angular-lb lotaris/nginx-angular-lb

    - name: Start Glassfish nodes container for todolist backend
      command: docker run -dP --volumes-from gf-data --link /mysql-srv:mysql-srv --link /serf-gf-cluster:serf-gf-cluster --env NODE_NAME=gf-node-{{ item }} --name gf-node-{{ item }} lotaris/glassfish-node
      with_sequence: count=2

    - name: Start the frontend application containers
      command: docker run -dP --volumes-from nginx-angular-data --link /serf-gf-cluster:serf-gf-cluster --env NODE_NAME=nginx-angular-node-{{ item }} --name nginx-angular-node-{{ item }} lotaris/nginx-angular-node
      with_sequence: count=2
