- hosts: localhost

  vars:
    download_directory: /tmp/dl

  tasks:
    - name: Install yum packages
      yum: name={{ item }} state=present
      with_items:
        - wget
        - unzip
        - supervisor

    - name: Create download directory in temp file
      file: path={{ download_directory }} state=directory

    - name: Download serf
      command: wget -O {{ download_directory }}/serf.zip https://dl.bintray.com/mitchellh/serf/0.6.3_linux_amd64.zip

    - name: Install serf
      unarchive: src={{ download_directory }}/serf.zip dest=/usr/bin copy=yes creates=/usr/bin/serf

    - name: Clean the download directory
      file: path={{ download_directory }} state=absent

    - name: Create serf scripts directory
      file: path=/serfScripts state=directory

    - name: Install scripts
      copy: src=files/{{ item }} dest=/serfScripts/{{ item }} mode=755
      with_items:
        - start-serf.sh

    - name: Create supervisor data directories
      file: path=/supervisor state=directory

    - name: Copy the configuration of the supervisor
      copy: src=files/supervisord.conf dest=/etc/supervisord.d/serf.ini
