- hosts: localhost

  vars:
    glassfish_user: glassfish
    glassfish_group: glassfish

    glassfish_root: /glassfish4
    glassfish_home: "{{ glassfish_root }}/glassfish"
    glassfish_asadmin: "{{ glassfish_home }}/bin/asadmin"

    asadmin_password: adminadmin
    asadmin_password_file: "{{ glassfish_root }}/bin/PASSWORD_FILE"

    backend_demoapp_db_user: todolist
    backend_demoapp_db_pass: todolist
    backend_demoapp_db_name: TODOLIST

    mysql_host: mysql-srv
    mysql_port: 3306

    serf_envvar_addr: serf-gf-cluster
    serf_envvar_port: 7946

  tasks:
    - name: Install scripts
      template: src=templates/start-serf.sh.j2 dest=/serfScripts/start-serf.sh mode=755

    - name: Create supervisor data directories
      file: path=/supervisor state=directory

    - name: Copy the configuration of the supervisor
      copy: src=files/supervisord.conf dest=/etc/supervisord.d/gf-node.ini

    - name: Start glassfish
      command: /bin/su {{ glassfish_user }} -c "{{ glassfish_asadmin }} start-domain domain1"

    - name: Enable admin console from remote host
      command: /bin/su {{ glassfish_user }} -c "{{ glassfish_asadmin }} --user admin --passwordfile {{ asadmin_password_file }} --host localhost --port 4848 enable-secure-admin"

    - name: Add connection pool
      command: /bin/su {{ glassfish_user }} -c "{{ glassfish_asadmin }} --user admin --passwordfile {{ asadmin_password_file }} --host localhost --port 4848 create-jdbc-connection-pool --datasourceclassname com.mysql.jdbc.jdbc2.optional.MysqlXADataSource --steadypoolsize 5 --maxpoolsize 50 --maxwait 60000 --idletimeout 300 --isconnectvalidatereq=true --validationmethod meta-data --restype javax.sql.XADataSource --property DatabaseName={{ backend_demoapp_db_name }}:ServerName={{ mysql_host }}:port={{ mysql_port }}:password={{ backend_demoapp_db_pass }}:user={{ backend_demoapp_db_user }} todolist-pool"

    - name: Add JDBC resource
      command: /bin/su {{ glassfish_user }} -c "{{ glassfish_asadmin }} --user admin --passwordfile {{ asadmin_password_file }} --host localhost --port 4848 create-jdbc-resource --enabled=true --connectionpoolid todolist-pool jdbc/todolist"
