- hosts: localhost

  vars:
    application_path: /rox
    application_version: angular
    application_secret_key_base: 6d3cbf5065a5039611b50e00e3fb3cd97e6dbefd7aedbd2707be2e29f9a056f46153915d7c8d9cddf6ea6aeefa0f507a53e1faa82e2440b48b9fbfaa0e4da615

    unicorn_uid: 4202
    unicorn_user: unicorn
    unicorn_group: unicorn

    postgres_port: 5432
    postgres_host: pg-srv
    postgres_user: rox-center
    postgres_pass: rox-center
    postgres_db: rox-center

    redis_port: 6379
    redis_host: redis-srv

  tasks:
    - name: Change rights to the ROX directory
      file: path={{ application_path }} owner={{ unicorn_user }} group={{ unicorn_group }} recurse=yes state=directory

    - name: Copy configuration files
      template: src=templates/{{ item }}.j2 dest={{ application_path }}/config/{{ item }} owner={{ unicorn_user }} group={{ unicorn_group }}
      with_items:
        - unicorn.rb
        - database.yml
        - redis.yml
        - rox-center.yml
        - secrets.yml

    - name: Install bundle
      shell: /bin/su {{ unicorn_user }} -l -c "cd {{ application_path }} && RAILS_ENV=production bundle install --deployment --without test development"

    - name: Precompile the assets
      shell: /bin/su {{ unicorn_user }} -l -c "cd {{ application_path }} && RAILS_ENV=production bundle exec rake assets:precompile"
