- hosts: localhost

  vars:
    jenkins_user: jenkins
    jenkins_group: jenkins

    download_directory: /tmp/dl

    mysql_user: todolist
    mysql_pass: todolist

  tasks:
    - name: Start Jenkins
      service: name=jenkins state=started

    - name: Create download directory in temp file
      file: path={{ download_directory }} state=directory

    - name: Do a break to let Jenkins to be ready
      pause: seconds=30

    - name: Download jenkins client
      command: wget -O {{ download_directory }}/jenkins-cli.jar http://localhost:8080/jnlpJars/jenkins-cli.jar

    - name: Create temp jobs directory
      file: path={{ download_directory }}/jobs state=directory

    - name: Copy the jobs
      template: src=templates/{{ item }}.xml.j2 dest={{ download_directory }}/jobs/{{ item }}.xml
      with_items:
        - deploy-todo-list-backend

    - name: Install the jobs
      shell: java -jar {{ download_directory }}/jenkins-cli.jar -s http://localhost:8080 create-job {{ item }} < {{ download_directory }}/jobs/{{ item }}.xml
      with_items:
        - deploy-todo-list-backend

    - name: Create maven user directory
      file: path=/home/{{ jenkins_user }}/.m2 group={{ jenkins_group }} owner={{ jenkins_user }} state=directory

    - name: Install the maven settings bootstrap configuration file
      template: src=templates/msb.yml.j2 dest=/home/{{ jenkins_user }}/.m2/msb.yml group={{ jenkins_group }} owner={{ jenkins_user }}

    - name: Clean the download directory
      file: path={{ download_directory }} state=absent
