- hosts: localhost

  vars:
    postgres_user: postgres
    postgres_uid: 4201
    postgres_group: postgres

  tasks:
    - name: Add postgres group
      group: name={{ postgres_group }} state=present

    - name: Create postgres user
      user: name={{ postgres_user }} group={{ postgres_group }} uid={{ postgres_uid }} state=present

    - name: Ensure postgres is installed.
      yum: pkg=postgresql-server state=installed enablerepo=epel

    # - name: Set the rights to the data directory
    #   file: path=/data owner={{ postgres_user }} group={{ postgres_group }} state=directory
